/**
 * Billing: subscriptions, payments, credits.
 *
 * Key rule: the source of truth for access is THESE TABLES, updated by Stripe
 * webhooks. The application never calls the Stripe API to render a page.
 *
 * All money amounts are integers in the currency's minor unit (cents).
 * Floating point is never used for money.
 */
import {
  pgTable,
  text,
  uuid,
  timestamp,
  integer,
  boolean,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { users } from "./users";

/** Subscription statuses — mirrors Stripe's nomenclature. */
export const SUBSCRIPTION_STATUSES = [
  "trialing",
  "active",
  "past_due",
  "canceled",
  "unpaid",
  "incomplete",
] as const;

export const subscriptions = pgTable(
  "subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    stripeSubscriptionId: text("stripe_subscription_id").notNull(),
    /** One of SUBSCRIPTION_STATUSES. */
    status: text("status").notNull(),
    priceId: text("price_id").notNull(),
    /** Paid-through date. Access checks read this field. */
    currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }).notNull(),
    /** User clicked "cancel", but access remains until the period ends. */
    cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("subscriptions_stripe_key").on(t.stripeSubscriptionId),
    index("subscriptions_user_idx").on(t.userId),
  ],
);

/**
 * Payment history for the Billing tab.
 * Populated exclusively by webhooks — never on the user's return to the site.
 */
export const payments = pgTable(
  "payments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    stripePaymentIntentId: text("stripe_payment_intent_id").notNull(),
    /** Amount in cents. */
    amountCents: integer("amount_cents").notNull(),
    currency: text("currency").notNull().default("usd"),
    status: text("status").notNull(),
    description: text("description"),
    /** Link to the PDF invoice generated by Stripe. We generate none ourselves. */
    invoiceUrl: text("invoice_url"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("payments_stripe_key").on(t.stripePaymentIntentId),
    index("payments_user_created_idx").on(t.userId, t.createdAt),
  ],
);

/**
 * Prepaid credit balance for API usage.
 *
 * Prepaid, not postpaid: a client cannot run up a bill worth thousands and
 * walk away — the GPU time would already be spent.
 */
export const credits = pgTable("credits", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  balanceCents: integer("balance_cents").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Journal of processed Stripe webhooks.
 *
 * Stripe delivers "at least once", so an event may arrive twice. The unique
 * key on event_id makes processing idempotent: a duplicate simply fails the
 * insert.
 */
export const processedEvents = pgTable(
  "processed_events",
  {
    stripeEventId: text("stripe_event_id").primaryKey(),
    type: text("type").notNull(),
    processedAt: timestamp("processed_at", { withTimezone: true }).notNull().defaultNow(),
  },
);
